# docker-compose.yml

services:
  # 백엔드 FastAPI 서비스
  stt-service:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지 빌드
    build: .
    container_name: stt_service_container
#    platform: linux/amd64
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    # [중요] FastAPI 실행 명령어를 여기에 지정
    command: gunicorn -k uvicorn.workers.UvicornWorker -w 1 -b 0.0.0.0:8080 app.app:app