# docker-compose.yml

# 'version' 속성은 최신 Docker Compose에서 더 이상 필요하지 않아 제거했습니다.
services:
  # 백엔드 서비스 이름 (예: stt-service)
  stt-service:
    # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    build: .
    # 컨테이너 이름을 지정하여 관리의 편의성을 높입니다.
    container_name: stt_service_container
    # .env 파일의 환경변수를 컨테이너에 주입합니다.
    env_file:
      - ./.env
    # 포트 매핑: 호스트의 8282번 포트를 컨테이너의 8000번 포트로 연결합니다.
    # main.py에서 8282 포트를 사용하므로, 호스트 포트를 8282로 설정했습니다.
    ports:
      - "8282:8000"
    # 재시작 정책: 컨테이너가 중지되면 (오류 발생 등), 사용자가 직접 중지하지 않는 한 항상 다시 시작합니다.
    #restart: unless-stopped